extra-package-dbs: []
packages:
- '.'

resolver: lts-16.12

extra-deps:
- superrecord-0.5.1.0@sha256:b05ffddd8e1b504f8dad7a9726c1489caa1fcd3e2460f8bda44b2baa6e2a76fb,2480

nix:
  packages: [ zlib, gmp ]
